version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: khipodb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-api:
    container_name: event-manager-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.production

volumes:
  postgres_data:
